version: 2

formats:
  - pdf

sphinx:
  configuration: docs/source/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
    nodejs: "19"
  jobs:
    pre_build:
      - npm install -g @bazel/bazelisk
      - bazel run //:install_sphinx_sources
      - env
      - find .
    post_build:
      - find .

python:
  install:
    - requirements: docs/requirements.txt
